== Creating consumers
To create a consumer simply create a class that contains `@PulsarConsumer` annotation with topics list.

[source,java]
----
import io.micronaut.configuration.pulsar.annotation.PulsarListener;
import io.micronaut.configuration.pulsar.annotation.PulsarConsumer;

@PulsarListener
public class SampleListener {
    @PulsarConsumer(topics = ["persistant://public/default/test"], messageBodyType=String.class)
    public void receive(String msg) {
        System.out.println("Received: " + msg);
    }
}
----

=== Using @PulsarListener annotation
This annotation servers to mark class as bean which should process Pulsar consumer messages. Here you can set non-required
properties `subscriptionName` which sets Pulsar consumer subscription name to custom defined string, `subscriptionType`
to one of Pulsars subscription types Exclusive, Failover, Shared, Key_Shared; and acknowledgment group timeout.

|===
|Property |Default |Description

|String subscriptionName
|
|Blank string as default which will let pulsar processor generate name for it

|SubscriptionType subscriptionType
|Exclusive
|Default as in Pulsar official Java library

|String ackGroupTimeout
|
|Must be Duration parsable string.
|===


=== Using @PulsarConsumer annotation
This is a method annotation. To use it you must specify either `String[] topics` option or `String topicsPattern`.
Topics option is parsed first so setting both values will make parser ignore topicsPattern.
|===
|Property |Default |Description

|String[] topics
|
|Required unless topicsPattern is specified. Has priority over topicsPattern

|Class<?> messageBodyType
|byte[].class
|Type of message to expect from Pulsar topic

|MessageSchema schemaType
|MessageSchema.BYTES or MessageSchema.JSON
|If body is specified other than byte it will default to JSON if not set manually. Currently, only supports BYTES, JSON, AVRO, PROTOBUF, KEY_VALUE.

|String consumerName
|
|Consumer name, not required

|RegexSubscriptionMode subscriptionTopicsMode
|
|In case topicsPattern is set this one can be one of PersistentOnly, NonPersistentOnly, AllTopics. Not required, set by
Pulsar library if not defined.

|boolean subscribeAsync
|true
|Whether to use async when reading Pulsar messages or not.

|===